/**
 * ASP Net Core Rest Remates Core
 * Rest Api de Remante en Linea y Core
 *
 * OpenAPI spec version: v1
 * Contact: agutierrez@plataformagroup.cl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LoginRequest { 
    usuario?: string;
    pass?: string;
}