/**
 * ASP Net Core Rest Remates Core
 * Rest Api de Remante en Linea y Core
 *
 * OpenAPI spec version: v1
 * Contact: agutierrez@plataformagroup.cl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UsuarioRequest { 
    pe_email?: string;
    pe_fechaingreso?: Array<Date>;
    pe_nombrecompleto?: string;
    pe_rut?: string;
    us_consuser?: string;
    us_esvigente?: string;
    us_intentosfallidos?: number;
    us_password?: string;
    pe_nombres?: string;
    pe_appaterno?: string;
    pe_apemanterno?: string;
    pe_tiporut?: number;
    pe_telefono?: string;
    comuna?: string;
    ciudad?: string;
    direccion?: string;
    pe_tipoDocumento?: number;
    us_bloqueado?:string;
}