/**
 * ASP Net Core Rest Remates Core
 * Rest Api de Remante en Linea y Core
 *
 * OpenAPI spec version: v1
 * Contact: agutierrez@plataformagroup.cl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsuarioRequest } from './usuarioRequest';

export interface UsuarioRequestPaginacion { 
    order?: string;
    field?: number;
    pagina?: number;
    cantidad?: number;
    consulta?: UsuarioRequest;
    resultado?: any;
    codigo?: string;
    numero?: number;
    mensaje?: string;
    total?: number;
}